/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/*STEPS:
1. Create user tasks (prototype and definition)
2. Stack pointer Selection
3. Configure Systick
        Find desired value
        Use SYST_SVR for settings
        Use SYST_SCSR for enabling systick
*/

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

//Step 1a
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void init_systick_timer(uint32_t tick_hz);
void SysTick_Handler(void);
__attribute ((naked)) void init_schedule_stack (uint32_t SSP_Top);
void init__tasks_stack(void);
void enable_processor_fault(void);
__attribute ((naked)) void switch_sp_to_psp(void);
uint32_t get_psp_value(void);
void save_psp(uint32_t current_psp);
void update_to_next_psp(void);
void init_tasks(void);

/*uint32_t psp_of_tasks[MAX_TASK] = {T1_STACK_START,T2_STACK_START,T3_STACK_START,T4_STACK_START};
uint32_t task_handler[4];*/
uint32_t current_task = 0;

typedef struct{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASK];

int main(void)
{
	enable_processor_fault();

	init_schedule_stack(SCH_STACK_START);

    init_tasks();

    init__tasks_stack();

   	led_init_all();

   	init_systick_timer(TICK_HZ);

    switch_sp_to_psp();

    task1_handler();


	while(1);
}

//Step 1b
void task1_handler(void){
	//These tasks do not end.So do in always true loop
	while(1){
		led_on(LED_GREEN);
		delay(DELAY_COUNT_1S);//1s
		led_off(LED_GREEN);
		delay(DELAY_COUNT_1S);//1s
	}
}
void task2_handler(void){
	while(1){
		led_on(LED_ORANGE);
		delay(DELAY_COUNT_500MS);//500ms
		led_off(LED_ORANGE);
		delay(DELAY_COUNT_500MS);//500ms
	}
}
void task3_handler(void){
	while(1){
		led_on(LED_RED);
		delay(DELAY_COUNT_250MS);//250ms
		led_off(LED_RED);
		delay(DELAY_COUNT_250MS);//250ms
	}
}
void task4_handler(void){
	while(1){
		led_on(LED_BLUE);
		delay(DELAY_COUNT_125MS);//125ms
		led_off(LED_BLUE);
		delay(DELAY_COUNT_125MS);//125ms
	}
}

void init_systick_timer(uint32_t tick_hz){
	uint32_t Delay_value = (uint32_t) (SysTick_count_clock/tick_hz)-1;
	uint32_t *pSRVR = (uint32_t*)0XE000E014;
	uint32_t *pSCSR = (uint32_t*)0XE000E010;
	*pSRVR &= ~(0X00FFFFFF);//since [31:24] are reserved (Clear the register)
	*pSRVR = Delay_value;//load delay value in SYST_RVR
	*pSCSR |= (1 << 1);//TICKINT BIT
	*pSCSR |= (1 << 2);//CLK SOURCE BIT
	*pSCSR |= (1 << 0);//ENABLING THE SYSTICK TIMER [0];

}

void SysTick_Handler(void){
	//Save the context of current task
	__asm volatile("MRS R0,PSP");
	__asm volatile("STMDB R0!,{R4-R11}");
	__asm volatile("PUSH {LR}");
	__asm volatile("BL save_psp");

	//Retrieve context of next task
	__asm volatile("BL update_to_next_psp");
	__asm volatile("BL get_psp_value");
	__asm volatile("LDMDB R0!,{R4-R11}");
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");



}

__attribute__((naked)) void init_schedule_stack (uint32_t SSP_Top){
	__asm volatile("MSR MSP,%0"::"r"(SSP_Top));
	__asm volatile("BX LR");
}

void save_psp(uint32_t current_psp){
	user_tasks[current_task].psp_value=current_psp;
}
void update_to_next_psp(void){
	current_task++;
	current_task%=MAX_TASK;//round robin fashion
}
uint32_t get_psp_value(void){
	return user_tasks[current_task].psp_value;
}
void init__tasks_stack(void){
	uint32_t *pPSP;
	for(int i=0;i<MAX_TASK;i++){
		*pPSP = (uint32_t) user_tasks[i].psp_value;
		//Stack Frame
		pPSP--;//xpsr
		*pPSP = DUMMY_xPSR;

		pPSP--;//PC
		*pPSP = (uint32_t) user_tasks[i].task_handler;

		pPSP--;//LR
		*pPSP = DUMMY_LR;

		//R1-R12
		for(int j=0;j<12;j++){
			pPSP--;
			*pPSP = 0;
		}
		user_tasks[i].psp_value=(uint32_t)pPSP;
	}
}
void enable_processor_fault(void){
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |=(1<<16);//MemManage
	*pSHCSR |=(1<<16);//BusFault
	*pSHCSR |=(1<<16);//UsageFault


}

void HardFault_Handler(void){
	printf("HardFault Exception\n");
}

void MemManage_Handler(void){
	printf("MemManage Exception\n");
}

void BusFault_Handler(void){
	printf("BusFault Exception\n");
}

void UsageFault_Handler(void){
	printf("UsageFault Exception\n");
}

__attribute ((naked)) void switch_sp_to_psp(void){
	__asm volatile("PUSH {LR}");//save the LR to return to main
	__asm volatile("BL get_psp_value");//Branch to get psp of task and link the return address
	//Now the result is stored in R0
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}");

	//change sp to psp using control
    __asm volatile("MOV R0,#0x02");//set 2nd bit of control register
    __asm volatile("MSR CONTROL,R0");
    __asm volatile("BX LR");//since it is a naked function we need to return manually using LR
}
void init_tasks(void){
	//Initially all the tasks are in raedy state
	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;

	//Intially the private stack values
	user_tasks[0].psp_value = T1_STACK_START;
	user_tasks[1].psp_value = T2_STACK_START;
	user_tasks[2].psp_value = T3_STACK_START;
	user_tasks[3].psp_value = T4_STACK_START;

	//Initialize their task handlers
	user_tasks[0].task_handler = task1_handler;
	user_tasks[1].task_handler = task2_handler;
	user_tasks[2].task_handler = task3_handler;
	user_tasks[3].task_handler = task4_handler;
}
